# fly.toml app configuration file generated for vagalivre-backend on 2024-04-25T00:27:27-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vagalivre-backend'
primary_region = 'gig'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
