CREATE TABLE parking_space
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active_resevation_id INTEGER,
    park_id              INTEGER,
    CONSTRAINT pk_parking_space PRIMARY KEY (id)
);

CREATE TABLE parking_space_resevations
(
    park_space_id  INTEGER NOT NULL,
    resevations_id INTEGER NOT NULL
);

CREATE TABLE parks
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    description   VARCHAR(255),
    hourly_rate   DOUBLE PRECISION,
    contact_info  VARCHAR(255),
    start_time    TIMESTAMP WITHOUT TIME ZONE,
    end_date_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_parks PRIMARY KEY (id)
);

CREATE TABLE person
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    email        VARCHAR(255),
    birth_day    TIMESTAMP WITHOUT TIME ZONE,
    phone_number VARCHAR(255),
    CONSTRAINT pk_person PRIMARY KEY (id)
);

CREATE TABLE reservation
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    park_id     INTEGER,
    start_time  time WITHOUT TIME ZONE,
    author_id   INTEGER,
    hourly_rate DOUBLE PRECISION,
    CONSTRAINT pk_reservation PRIMARY KEY (id)
);

ALTER TABLE parking_space_resevations
    ADD CONSTRAINT uc_parking_space_resevations_resevations UNIQUE (resevations_id);

ALTER TABLE parking_space
    ADD CONSTRAINT FK_PARKING_SPACE_ON_ACTIVE_RESEVATION FOREIGN KEY (active_resevation_id) REFERENCES reservation (id);

ALTER TABLE parking_space
    ADD CONSTRAINT FK_PARKING_SPACE_ON_PARK FOREIGN KEY (park_id) REFERENCES parks (id);

ALTER TABLE reservation
    ADD CONSTRAINT FK_RESERVATION_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES person (id);

ALTER TABLE reservation
    ADD CONSTRAINT FK_RESERVATION_ON_PARK FOREIGN KEY (park_id) REFERENCES parks (id);

ALTER TABLE parking_space_resevations
    ADD CONSTRAINT fk_parspares_on_park_space FOREIGN KEY (park_space_id) REFERENCES parking_space (id);

ALTER TABLE parking_space_resevations
    ADD CONSTRAINT fk_parspares_on_reservation FOREIGN KEY (resevations_id) REFERENCES reservation (id);