CREATE TABLE park
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    description   VARCHAR(255),
    hourly_rate   DOUBLE PRECISION,
    contact_info  VARCHAR(255),
    start_time    TIMESTAMP WITHOUT TIME ZONE,
    end_date_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_park PRIMARY KEY (id)
);

CREATE TABLE park_space
(
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active_reservation_id INTEGER,
    park_id               INTEGER,
    CONSTRAINT pk_parkspace PRIMARY KEY (id)
);

CREATE TABLE park_space_reservations
(
    park_space_id   INTEGER NOT NULL,
    reservations_id INTEGER NOT NULL
);

CREATE TABLE person
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    email        VARCHAR(255),
    birth_day    TIMESTAMP WITHOUT TIME ZONE,
    phone_number VARCHAR(255),
    CONSTRAINT pk_person PRIMARY KEY (id)
);

CREATE TABLE reservation
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    park_id     INTEGER,
    start_time  time WITHOUT TIME ZONE,
    author_id   INTEGER,
    hourly_rate DOUBLE PRECISION,
    CONSTRAINT pk_reservation PRIMARY KEY (id)
);

ALTER TABLE park_space_reservations
    ADD CONSTRAINT uc_park_space_reservations_reservations UNIQUE (reservations_id);

ALTER TABLE park_space
    ADD CONSTRAINT FK_PARKSPACE_ON_ACTIVE_RESERVATION FOREIGN KEY (active_reservation_id) REFERENCES reservation (id);

ALTER TABLE park_space
    ADD CONSTRAINT FK_PARKSPACE_ON_PARK FOREIGN KEY (park_id) REFERENCES park (id);

ALTER TABLE reservation
    ADD CONSTRAINT FK_RESERVATION_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES person (id);

ALTER TABLE reservation
    ADD CONSTRAINT FK_RESERVATION_ON_PARK FOREIGN KEY (park_id) REFERENCES park (id);

ALTER TABLE park_space_reservations
    ADD CONSTRAINT fk_parspares_on_park_space FOREIGN KEY (park_space_id) REFERENCES park_space (id);

ALTER TABLE park_space_reservations
    ADD CONSTRAINT fk_parspares_on_reservation FOREIGN KEY (reservations_id) REFERENCES reservation (id);